dev:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:       'mysql:host=localhost;dbname=DATABASENAME;port=3306'
      username:  redaktor
      password:  tajnehaslo
      charset:   utf8
